baseURL = "https://wchajl.github.io"
languageCode = "zh-cn"
title = "HoustonWang"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
